version: "3"

services:
  node:
    image: node:16.14

    container_name: chat

    build: ./

    tty: true

    stdin_open: true

    command: bash

    restart: always

    working_dir: /app

    volumes:
      - ./:/app

    depends_on:
      - mongodb

    ports:
      - 8080:8080

    environment:
      - MONGO_URI=mongodb://localhost:27017/Chat

  mongodb:
    image: mongo:5.0.7
    container_name: chat_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: chat_net
